### ISSUE TITLE
Individual Contact Pages for Officers

### ISSUE THREAD

**Issue by Fromalaska49** [UTSA-ACM/ACM-Website#43]
We need an individualized contact page for each officer, that way officers can be individually contacted without publishing their personal email. The easiest way would be to automatically send an email.

**Comment by soethanv** [comment]
This sounds like a really good idea. What do we need to make this happen?

**Comment by Fromalaska49** [comment]
It would need to be done server-side to protect the privacy of emails

**Comment by Fromalaska49** [comment]
Of course there needs to be a front end for it as well, something like this: http://andrewhutton.me/contact
