### ISSUE TITLE
Missing SSL on Pay Dues Page

### ISSUE THREAD

**Issue by soethanv** [UTSA-ACM/ACM-Website#68]
![screenshot1](https://user-images.githubusercontent.com/22684339/45311839-0abb5500-b4f0-11e8-95ed-416181c12b48.png)

**Comment by Fromalaska49** [comment]
You will have a secure connection if you access the page via https instead of http

**Comment by Fromalaska49** [comment]
We can force everything through https for the payment processing, just to user-proof it

**Comment by soethanv** [comment]
Forcing everything through https would be more suitable. I didn't try changing to https at first. But you are right. Users could simply put https instead of http.
